In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.ensemble import BaggingClassifier,BaggingRegressor
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.metrics import r2_score,accuracy_score
from sklearn.datasets import load_iris,make_classification,fetch_california_housing
from sklearn.svm import SVC,SVR

In [7]:
X,y=make_classification(n_samples=1000,n_features=10,n_informative=3)

In [8]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [9]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
accuracy_score(y_test,dt.predict(x_test))

0.93

In [21]:
bag=BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.25,
    bootstrap=False,
    random_state=42
)

In [22]:
bag.fit(x_train,y_train)
accuracy_score(y_test,bag.predict(x_test))

0.955

In [26]:
svc=SVC()
svc.fit(x_train,y_train)
accuracy_score(y_test,svc.predict(x_test))

0.93

In [24]:
bag=BaggingClassifier(
    estimator=SVC(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    random_state=42
)

In [25]:
bag.fit(x_train,y_train)
accuracy_score(y_test,bag.predict(x_test))

0.89

In [41]:
bag=BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=1.0,
    bootstrap=True,
    random_state=42,
    max_features=0.5,
    oob_score=True            ###oob score-- out of bag score, helps because if boostrap=True, sometimes a particualr row might not be in any row or some might be in all, statistically only 63% are used. So oob parameter utilises the rest of 37%
)

In [40]:
cross_val_score(bag,X,y,cv=5).mean()

np.float64(0.943)

In [45]:
X,y=fetch_california_housing(return_X_y=True)

In [56]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [51]:
df=pd.DataFrame(X,columns=fetch_california_housing().feature_names)
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [53]:
df['target']=y

In [54]:
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [57]:
dt=DecisionTreeRegressor()
dt.fit(x_train,y_train)
r2_score(y_test,dt.predict(x_test))

0.6272906601917361

In [59]:
bag=BaggingRegressor(
    estimator=DecisionTreeRegressor(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    random_state=42
)
bag.fit(x_train,y_train)
r2_score(y_test,bag.predict(x_test))

0.7862664631848938

In [60]:
lr=LinearRegression()
lr.fit(x_train,y_train)
r2_score(y_test,lr.predict(x_test))

0.5757877060324524

In [62]:
bag=BaggingRegressor(
    estimator=LinearRegression(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    random_state=42
)
bag.fit(x_train,y_train)
r2_score(y_test,bag.predict(x_test))

0.5831180972916483

In [65]:
knn=KNeighborsRegressor()
knn.fit(x_train,y_train)
r2_score(y_test,lr.predict(x_test))

0.5757877060324524

In [66]:
bag=BaggingRegressor(
    estimator=KNeighborsRegressor(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    random_state=42
)
bag.fit(x_train,y_train)
r2_score(y_test,bag.predict(x_test))

0.13148915076146184

In [68]:
svr=SVR()
svr.fit(x_train,y_train)
r2_score(y_test,svr.predict(x_test))

-0.01648536010717372

In [71]:
bag=BaggingRegressor(
    estimator=SVR(),
    n_estimators=100,
    max_samples=0.25,
    bootstrap=True,
    random_state=42
)
bag.fit(x_train,y_train)
r2_score(y_test,bag.predict(x_test))

-0.03821982211713415