In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.metrics import r2_score,mean_squared_error,precision_score,recall_score,f1_score,accuracy_score,confusion_matrix

In [14]:
from sklearn.datasets import make_classification
size=6
raw_array = np.random.rand(size)            ###Standard_Normalization
random_weights = raw_array / np.sum(raw_array)
X,y = make_classification(n_samples=1000, n_features=4,n_informative=4,n_redundant=0,weights=random_weights,n_classes=size, n_clusters_per_class=1,random_state=43)

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=41)
df=pd.Series(y_train)
df.value_counts()

5    220
0    163
3    149
4    137
1    111
2     20
Name: count, dtype: int64

In [16]:
lrc=LogisticRegression(multi_class='multinomial')
lrc.fit(X_train,y_train)
lrc.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

array([0, 5, 5, 4, 5, 3, 3, 0, 4, 0, 4, 4, 0, 5, 5, 5, 1, 4, 5, 4, 0, 5,
       3, 0, 1, 5, 1, 4, 3, 0, 4, 4, 0, 5, 5, 3, 3, 1, 3, 5, 3, 0, 0, 5,
       3, 4, 5, 5, 3, 3, 3, 4, 3, 5, 3, 1, 0, 3, 3, 4, 0, 5, 5, 0, 0, 3,
       4, 4, 0, 3, 0, 1, 5, 5, 0, 5, 5, 0, 0, 4, 0, 5, 5, 0, 0, 4, 3, 0,
       0, 4, 4, 4, 5, 3, 1, 0, 4, 4, 0, 5, 3, 0, 4, 5, 5, 0, 4, 5, 5, 1,
       0, 5, 1, 5, 5, 5, 5, 0, 1, 3, 4, 3, 4, 1, 5, 4, 3, 0, 4, 4, 0, 4,
       5, 1, 3, 5, 3, 4, 5, 4, 0, 4, 3, 5, 3, 3, 4, 1, 5, 0, 5, 4, 0, 4,
       5, 3, 2, 4, 0, 3, 1, 4, 5, 4, 5, 3, 4, 4, 3, 1, 5, 1, 3, 1, 4, 3,
       0, 0, 4, 0, 0, 5, 3, 4, 3, 4, 5, 5, 4, 4, 5, 3, 4, 3, 5, 1, 4, 1,
       3, 5])

In [9]:
lrc.coef_

array([[ 0.18379734,  0.75447068,  0.35152621,  1.44363481],
       [-0.81805152, -0.5527796 ,  0.32116915, -0.83258814],
       [-1.33378653,  0.97605658,  0.48155857, -0.10435878],
       [ 1.01084122,  0.49160207, -1.12530209, -1.01860072],
       [ 0.81309258, -0.96261445,  0.45533851,  1.12477671],
       [ 0.14410691, -0.70673528, -0.48429035, -0.61286388]])

In [10]:
lrc.intercept_

array([ 0.57994507, -0.1939201 , -0.36473823, -0.86205036,  0.99341826,
       -0.15265465])

In [25]:
lrc.predict_proba(X_test)

array([[6.71608156e-01, 1.34108149e-01, 3.75350195e-02, 5.86667729e-03,
        1.49036788e-01, 1.84521066e-03],
       [3.33555731e-03, 8.39491076e-02, 4.99578989e-04, 4.30171969e-02,
        7.26801933e-02, 7.96518366e-01],
       [3.97191020e-02, 2.38214222e-01, 8.84640464e-03, 1.45183831e-01,
        5.50764078e-02, 5.12960033e-01],
       ...,
       [5.12126310e-02, 5.98102022e-01, 2.63179394e-01, 5.76013374e-02,
        7.89843310e-04, 2.91147723e-02],
       [1.40391266e-01, 2.19113488e-01, 3.08349451e-01, 3.19188251e-01,
        1.06942481e-04, 1.28506024e-02],
       [2.32474499e-02, 4.29113287e-02, 2.43207264e-03, 3.32309289e-01,
        1.18916039e-02, 5.87208256e-01]])

In [17]:
print(precision_score(y_test,lrc.predict(X_test),average='weighted'))
print(recall_score(y_test,lrc.predict(X_test),average='weighted'))
print(f1_score(y_test,lrc.predict(X_test),average='weighted'))
print(accuracy_score(y_test,lrc.predict(X_test)))

0.6459529352226722
0.64
0.6298603967609021
0.64

In [18]:
pd.DataFrame(confusion_matrix(y_test,lrc.predict(X_test)))

    0   1  2   3   4   5
0  27   1  0   6   7   2
1   2  10  0   3   7   3
2   0   3  1   1   0   1
3   4   0  0  26   4   9
4   6   3  0   0  30   3
5   1   2  0   4   0  34

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,lrc.predict(X_test)))

              precision    recall  f1-score   support

           0       0.75      0.75      0.75         8
           1       0.33      1.00      0.50         1
           2       0.78      0.64      0.70        11

    accuracy                           0.70        20
   macro avg       0.62      0.80      0.65        20
weighted avg       0.74      0.70      0.71        20

In [ ]:
class gradient_descent_logistic():
  def __init__(self,learning_rate,epochs):
    self.learning_rate=learning_rate
    self.epochs=epochs
    self.coef_=None
    self.intercept_=None
  def sigmoid(self,z):
    return 1/(1+np.exp(-z))
  def fit(self,X,y):
    X=np.insert(X,0,1,axis=1)
    self.coef_=np.ones(X.shape[1])
    for i in range(self.epochs):
      y_pred=self.sigmoid(np.dot(X,self.coef_))
      coef_der=np.dot(y_pred-y,X)/X.shape[0]
      self.coef_-=self.learning_rate*(coef_der)
    self.intercept_=self.coef_[0]
    self.coef_=self.coef_[1:]
  def predict(self,X,threshold):
    y_pred=self.sigmoid(np.dot(X,self.coef_)+self.intercept_)
    y_pred=np.where(y_pred>threshold,1,0)
    return y_pred

In [ ]:
gdlrc=gradient_descent_logistic(learning_rate=0.1,epochs=250)
gdlrc.fit(X_train,y_train)
gdlrc.predict(X_test,0.5)

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1])

In [ ]:
gdlrc.coef_

array([ 3.04999532, 13.97214306])

In [ ]:
gdlrc.intercept_

np.float64(0.24872474291550903)

In [ ]:
r2_score(y_test,gdlrc.predict(X_test))

0.9583108905072544

In [ ]:
r2_score(y_test,lrc.predict(X_test))

1.0

In [ ]:

print(precision_score(y_test,gdlrc.predict(X_test,0.5)))
print(recall_score(y_test,gdlrc.predict(X_test,0.5)))
print(f1_score(y_test,gdlrc.predict(X_test,0.5)))
print(accuracy_score(y_test,gdlrc.predict(X_test,0.5)))

1.0
1.0
1.0
1.0